version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console]

loggers:
  tortoise-client:
    level: DEBUG
    handlers: [console]
    propagate: no
